services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    container_name: backend
    env_file:
      - .env 

  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3302:3302"
    volumes:
      - mysql_data:/var/lib/mysql

  nextjs:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
    restart: always

volumes:
  mysql_data:

